### ISSUE TITLE
Very interesting idea

### ISSUE THREAD

**Issue by thejjmiller** [dmaier-couchbase/cb-graph#1]
I'm just curious. Was this created as an experiment or is it something that Couchbase is looking into as a supported product?  I have been looking into TitanDb which runs on Cassandra. However we already had Couchbase and was always wondering how difficult it would be to implement on that. 

After briefly looking into the way you are traversing graphs I noticed you may want to pull edge details out into a separate document once you hit a certain edge count otherwise you will end up having a super node problem.

**Comment by thejjmiller** [comment]
I would also be interested in contributing if you had any plans on continuing on building this. I have experience with OrientDb and learned a lot of stuff working with that project.

**Comment by dmaier-couchbase** [comment]
Hi,

yes. Having the adjacency list  separated is on the TODO list :-) . I should really better maintain the TODO-s as Github tasks.

Regards,
David

**Comment by dmaier-couchbase** [comment]
Hi,

just created a few GitHub tickets in order to make it a bit more transparent.

Regards,
David
